apiVersion: apps/v1
kind: Deployment
metadata:
  name: sb-unity-web-deployment
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: sb-unity-web
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: sb-unity-web-configmap-dev
              key: PORT
