apiVersion: apps/v1
kind: Deployment
metadata:
  name: sb-unity-web-deployment
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: sb-unity-web
        imagePullPolicy: Always
        image:  public.ecr.aws/e7g5w4c7/sb-unity-web:stage
        ports:
          - containerPort: 3000
        env:  
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: sb-unity-web-configmap-stage
              key: PORT